# Generated by Django 2.1.7 on 2019-03-30 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_firstLetter', models.CharField(max_length=10, null=True)),
                ('station_name', models.CharField(max_length=10, null=True, unique=True)),
                ('station_code', models.CharField(max_length=10, null=True, unique=True)),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='TrainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_date', models.DateField(null=True)),
                ('train_type', models.CharField(max_length=1, null=True)),
                ('train_num', models.IntegerField(max_length=5, null=True)),
                ('go_time', models.TimeField(null=True)),
                ('running_time', models.CharField(max_length=10, null=True)),
                ('is_morrow', models.BooleanField(default=0)),
                ('is_delete', models.BooleanField(default=0)),
                ('destination_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_train_info', to='train.Station')),
                ('origin_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_train_info', to='train.Station')),
            ],
            options={
                'db_table': 'train_info',
            },
        ),
        migrations.CreateModel(
            name='TrainStationPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_time', models.TimeField(null=True)),
                ('no_seat_nums', models.IntegerField(default=50, max_length=2)),
                ('no_seat_price', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('hard_seat_nums', models.IntegerField(default=50, max_length=2)),
                ('hard_seat_price', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('hard_berth_nums', models.IntegerField(default=50, max_length=2)),
                ('hard_berth_price', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('second_seat_nums', models.IntegerField(default=50, max_length=2)),
                ('second_seat_price', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('first_seat_nums', models.IntegerField(default=50, max_length=2)),
                ('first_seat_price', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('business_seat_nums', models.IntegerField(default=50, max_length=2)),
                ('business_seat_price', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('arrive_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrive_train_price', to='train.Station')),
                ('go_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='go_train_price', to='train.Station')),
                ('train_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_price', to='train.TrainInfo')),
            ],
            options={
                'db_table': 'train_price',
            },
        ),
    ]
