# Generated by Django 2.1.7 on 2019-03-30 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininfo',
            name='arrive_time',
            field=models.TimeField(null=True, verbose_name='到达时间'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='车站代号'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_firstLetter',
            field=models.CharField(max_length=10, null=True, verbose_name='车站首字母'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='站点名称'),
        ),
        migrations.AlterField(
            model_name='traininfo',
            name='destination_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_train_info', to='train.Station', verbose_name='终点站'),
        ),
        migrations.AlterField(
            model_name='traininfo',
            name='go_time',
            field=models.TimeField(null=True, verbose_name='出发时间'),
        ),
        migrations.AlterField(
            model_name='traininfo',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='traininfo',
            name='is_morrow',
            field=models.BooleanField(default=0, verbose_name='是否次日'),
        ),
        migrations.AlterField(
            model_name='traininfo',
            name='origin_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_train_info', to='train.Station', verbose_name='起点站'),
        ),
        migrations.AlterField(
            model_name='traininfo',
            name='running_time',
            field=models.CharField(max_length=10, null=True, verbose_name='运行时长'),
        ),
        migrations.AlterField(
            model_name='traininfo',
            name='train_date',
            field=models.DateField(null=True, verbose_name='运行日期'),
        ),
        migrations.AlterField(
            model_name='traininfo',
            name='train_num',
            field=models.IntegerField(null=True, verbose_name='火车编号'),
        ),
        migrations.AlterField(
            model_name='traininfo',
            name='train_type',
            field=models.CharField(max_length=1, null=True, verbose_name='火车类型'),
        ),
    ]
