# Generated by Django 2.1.7 on 2019-03-30 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20190330_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainstationprice',
            name='arrive_time',
            field=models.TimeField(null=True, verbose_name='到达时间'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='arrive_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrive_train_price', to='train.Station', verbose_name='到达站'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='business_seat_nums',
            field=models.IntegerField(default=50, verbose_name='商务座票数'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='business_seat_price',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='first_seat_nums',
            field=models.IntegerField(default=50, verbose_name='一等座票数'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='first_seat_price',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='go_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='go_train_price', to='train.Station', verbose_name='出发站'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='go_time',
            field=models.TimeField(null=True, verbose_name='出发时间'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='hard_berth_nums',
            field=models.IntegerField(default=50, verbose_name='硬卧票数'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='hard_berth_price',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='hard_seat_nums',
            field=models.IntegerField(default=50, verbose_name='硬座票数'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='hard_seat_price',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='no_seat_nums',
            field=models.IntegerField(default=50, verbose_name='无座票数'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='no_seat_price',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='second_seat_nums',
            field=models.IntegerField(default=50, verbose_name='二等座票数'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='second_seat_price',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='trainstationprice',
            name='train_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_price', to='train.TrainInfo', verbose_name='车次'),
        ),
    ]
