# Generated by Django 2.1.7 on 2019-03-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_auto_20190330_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': '站点信息', 'verbose_name_plural': '站点信息'},
        ),
        migrations.AlterModelOptions(
            name='traininfo',
            options={'verbose_name': '火车信息', 'verbose_name_plural': '火车信息'},
        ),
        migrations.AlterModelOptions(
            name='trainstationprice',
            options={'verbose_name': '火车票价', 'verbose_name_plural': '火车票价'},
        ),
    ]
