# Generated by Django 2.1.7 on 2019-03-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_auto_20190330_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininfo',
            name='train_type',
            field=models.CharField(choices=[('C', '城际列车 C'), ('D', '动车组 D'), ('G', '高速列车 G'), ('Z', '直达列车 Z'), ('T', '特快列车 T'), ('K', '快速列车 K'), ('L', '临时旅客列车 L'), ('A', '局管内临时旅客列车 A'), ('Y', '旅游列车 Y')], max_length=1, null=True, verbose_name='火车类型'),
        ),
    ]
