# Generated by Django 2.1.7 on 2019-03-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_auto_20190330_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininfo',
            name='is_delete',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], default=0, max_length=1, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='traininfo',
            name='is_morrow',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], default=0, max_length=1, verbose_name='是否次日'),
        ),
    ]
