# Generated by Django 2.1.7 on 2019-03-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(max_length=11, null=True, unique=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=10, null=True)),
                ('sex', models.BooleanField(default=0)),
                ('id_card', models.IntegerField(max_length=18, null=True, unique=True)),
                ('age', models.IntegerField(max_length=3)),
                ('phone', models.IntegerField(max_length=11, null=True, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
