# Generated by Django 2.1.7 on 2019-04-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190330_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='账号'),
        ),
    ]
