# Generated by Django 2.1.7 on 2019-03-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, null=True, unique=True)),
                ('account_num', models.IntegerField(max_length=11, null=True)),
                ('name', models.CharField(max_length=10, null=True)),
                ('id_card', models.IntegerField(max_length=18, null=True)),
                ('go_station', models.CharField(max_length=10, null=True)),
                ('go_time', models.CharField(max_length=10, null=True)),
                ('arrive_station', models.CharField(max_length=10, null=True)),
                ('arrive_time', models.CharField(max_length=10, null=True)),
                ('seat_level', models.CharField(max_length=10, null=True)),
                ('seat_price', models.CharField(max_length=10, null=True)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=0)),
                ('is_alter', models.BooleanField(default=0)),
            ],
        ),
    ]
