# Generated by Django 2.1.7 on 2019-03-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account_num',
            field=models.IntegerField(max_length=11, null=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='arrive_station',
            field=models.CharField(max_length=10, null=True, verbose_name='到达地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='arrive_time',
            field=models.CharField(max_length=10, null=True, verbose_name='到达时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='go_station',
            field=models.CharField(max_length=10, null=True, verbose_name='出发地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='go_time',
            field=models.CharField(max_length=10, null=True, verbose_name='出发时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_card',
            field=models.IntegerField(max_length=18, null=True, verbose_name='证件号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_alter',
            field=models.BooleanField(default=0, verbose_name='是否改签'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='是否退票'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=10, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='订票日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seat_level',
            field=models.CharField(max_length=10, null=True, verbose_name='座位级别'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seat_price',
            field=models.CharField(max_length=10, null=True, verbose_name='票价'),
        ),
    ]
