# Generated by Django 2.1.7 on 2019-03-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190330_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account_num',
            field=models.IntegerField(null=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_card',
            field=models.IntegerField(null=True, verbose_name='证件号'),
        ),
    ]
