# Generated by Django 2.1.7 on 2019-04-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190330_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_alter',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('1', '已支付'), ('2', '已改签'), ('3', '已退票')], null=True, verbose_name='状态'),
        ),
    ]
