# Generated by Django 2.1.7 on 2019-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190403_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.CharField(max_length=64, null=True, verbose_name='订票日期'),
        ),
    ]
