# Generated by Django 2.1.7 on 2019-04-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190417_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_card',
            field=models.CharField(max_length=18, null=True, unique=True, verbose_name='证件号'),
        ),
    ]
