# Generated by Django 2.1.7 on 2019-04-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190417_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, '已支付'), (2, '已改签'), (3, '已退票')], null=True, verbose_name='状态'),
        ),
    ]
