# Generated by Django 2.1.7 on 2019-04-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20190417_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='订单号'),
        ),
    ]
